export const amethystPages = [
  [`You feel the opening.`],
  [
    `A familiar sense of gently being called. `,
    `This time only in a whisper, `,
    `but you've become sensitive to the voice.`,
  ],
  [
    `You've traversed to this space several times now. `,
    `Instead of becoming more familiar, `,
    `it's only deepened in mystery.`,
  ],
  [`It's in equal parts awe and curiosity `, `that you decide...`],
  [`to step into the realm.`],
  [`~`],
  [
    `You slip between the recesses of time. `,
    `Slowly at first, in the way that warm honey drips from a dipper. `,
    `The minutes turn into colors and the hours turn into harmonies.`,
  ],
  [`The vaporization of it all creates a blinding myst all around you.`],
  [
    `You try to place your hand in front of you. `,
    `Is the fog so hazy? `,
    `Or is there no hand to see in the first place?`,
  ],
  [
    `The material language of this world begins to form. `,
    `Glints of a limitless ocean emerge below you. `,
    `The water is clear as crystal. `,
    `The sun is nowhere to be found.`,
  ],
  [
    `Instead, light radiates from the fog, revealing the water's lavender hue. `,
  ],
  [`While nothing else is in sight, `, `you know you are not alone here.`],
  [
    `Instinct tells you that a force inhabits this limen. `,
    `In the back of your mind are the echoes of visitors like you.`,
  ],
  [
    `Here, it's impossible to tell if sounds are with you in the present, `,
    `or if they function the way that starlight does —`,
    `where the glimmer shines years after the source disappears.`,
  ],
  [
    `You realize, for the first time after many visits, `,
    `that these echoes could even be reverberating from the future.`,
  ],
  [`~`],
  [`Where does the water get that color?`],
  [
    `You've often wondered if the gentle violet tint comes from the light, `,
    `or if you're seeing the sparkling water's natural color.`,
  ],
  [`The mirror below glistens like a gem.`],
  [
    `You find reverence in the reverie. `,
    `There's an opaque beauty to it. `,
    `A language of shape and sound on a canvas of time.`,
  ],
  [
    `In the abstract, you feel there's something being shown to you beyond words. `,
    `With every reach for a nominal descriptor, `,
    `you're only knocking on the door of what's here.`,
  ],
  [`So you keep coming back.`],
  [`To learn the exotic vernacular.\n`, `One stroke at a time.`],
  [
    `You're floating just above the water now. `,
    `The fog has cleared, showing an infinite horizon in all directions.`,
  ],
  [`~`],
  [
    `The lapping of the water sings into your ears. `,
    `You reach down. `,
    `Your reflection extends up in rhyme to touch the glass of the surface.`,
  ],
  [`You hear the drone first... `],
  [`...then `, `a gentle vibration sits at the edge of your vision.`],
  [
    `In the distance you see the starting pitch for Amethyst's melody. `,
    `A single sphere rings out a tuning sound, `,
    `inviting entrainment for the coming song.`,
  ],
  [
    `You know the tune, and yet you've never heard it. `,
    `The pitches change with each verse, but the cadence always reaches resolution.`,
  ],
  [
    `There's a deep Truth hiding in the mystery of this performance. `,
    `Each answer leads to more questions.`,
  ],
  [`You start to think you'll never reach the root.`],
  [
    `Why would any one come back\n`,
    `time and time again\n`,
    `only to become more lost?`,
  ],
  [`Thankfully, `, `it doesn't seem to matter.`],
  [`You realize `, `that the sweetness of the tone...`],
  [`...is in `, `the resonance `, `of it's harmonics.`],
  [`~`],
  [`You begin to sing.`],
];
