export const bookshelf = {
  // Sonic IDW comics
  SoManyBooks: {
    name: 'So Many Books',
    author: 'Gabriel Zaid',
    desc: "Natasha Wimmer's translation of a book on books.",
    progress: 'reading',
    slug: 'SoManyBooks',
    tags: ['writing'],
    image: 'https://covers.openlibrary.org/b/id/7145150-M.jpg',
    date: '2025-11-29',
  },
  WaltDisneyAnAmericanOriginal: {
    name: 'Walt Disney: An American Original',
    author: 'Bob Thomas',
    image: 'https://m.media-amazon.com/images/I/81KF74z+G6L._SY466_.jpg',
    progress: 'reading',
    date: '2025-11-10',
    slug: 'WaltDisneyAnAmericanOriginal',
    desc: 'Really captures the spirit and drive of the man. Inspiring to read about how deeply involved Disney was in the creation of his early films.',
    tags: ['biography', 'history', 'animation'],
  },
  ArtAndFear: {
    name: 'Art & Fear: Observations on the Perils (and Rewards) of Artmaking',
    author: 'David Bayles and Ted Orland',
    image: 'https://m.media-amazon.com/images/I/61YVr86jusL._SY466_.jpg',
    progress: 'reading',
    date: '2025-11-05',
    slug: 'ArtAndFear',
    desc: `Observations on the common pitfalls and roadblocks of art making across disciplines, and, of course, arguments for why it's still worth doing.`,
    tags: ['creativity'],
  },
  AgainstPlatforms: {
    name: 'Against Platforms: Surviving Digital Utopia',
    author: 'Mike Pepi',
    image: 'https://m.media-amazon.com/images/I/81s0wfvYUTL._AC_UY218_.jpg',
    progress: 'read',
    date: '2025-08-04',
    slug: 'AgainstPlatforms',
    rating: 7,
    desc: 'There was a time where rules on the web were being written via improvisation. Arguably we are still there, though the effect has transformed from thrilling to sour. This book is a critical look at some of the decisions that now shape large scale applications and how they are not sufficient replacements for human, non-commercial organizations.',
    tags: ['technology', 'non-fiction'],
  },
  ForceDynamicLifeDrawing: {
    name: 'FORCE: Dynamic Life Drawing',
    author: 'Mike Mattesi',
    image: 'https://m.media-amazon.com/images/I/91G54hgH1aL._SY385_.jpg',
    progress: 'reading',
    tags: ['artresource', 'drawing'],
    slug: 'ForceDynamicLifeDrawing',
    purchase:
      'https://www.amazon.com/FORCE-Dynamic-Drawing-Anniversary-Force/dp/1138919578',
    desc: `Figure drawing that puts rhythm and gesture front and center. This approach makes drawing the figure enjoyable and expressive. Fun to work through and a great companion to the Drawing Force online course.`,
    date: '2025-11-03',
  },
  ShunasJourney: {
    name: `Shuna's Journey`,
    author: 'Hayao Miyazaki',
    image: 'https://m.media-amazon.com/images/I/81w8MPT9fVL._SL1500_.jpg',
    progress: 'read',
    purchase:
      'https://www.amazon.com/Shunas-Journey-Hayao-Miyazaki/dp/1250846528',
    tags: ['comics', 'fiction', 'fantasy'],
    slug: 'ShunasJourney',
    date: '2025-07-18',
    desc: 'A beautiful jewel. Similar themes and set pieces to Nausicaä, but with a pacing that leaves a myst around the characters — the way that good fables do.',
  },
  TheAppleIIAge: {
    name: 'The Apple II Age: How the Computer Became Personal',
    author: 'Laine Nooney',
    image: 'https://m.media-amazon.com/images/I/712pxmzGJlL._SL1500_.jpg',
    progress: 'read',
    purchase:
      'https://www.amazon.com/Apple-II-Age-Computer-Personal/dp/0226840034',
    tags: ['non-fiction', 'history', 'technology'],
    slug: 'TheAppleIIAge',
    desc: `I appreciated the cultural context, since the 70s-80s are eras of personal computing I'm largely unfamiliar with. Though, that cultural context provided is not unbiased, novel, or nuanced. I'd have a hard time recommending it to other tech enthusiasts, as the account of events are largely joyless and shallow.`,
    date: '2025-07-18',
  },
  HomepageWebCraft: {
    name: `Homepage Web Craft`,
    author: 'Daniel Murray (Melon)',
    image:
      'https://res.cloudinary.com/cpadilla/image/upload/v1748802170/chrisdpadilla/blog/images/melonzine_gakdvg.webp',
    progress: 'read',
    date: '2025-06-01',
    slug: 'HopepageWebCraft',
    desc: 'Wild maximalist zine on making websites! A beautiful mess.',
    tags: ['comics', 'web', 'zine'],
    purchase: 'https://ko-fi.com/s/75df99623e',
  },
  SamAndMaxSurfinTheHighway: {
    name: `Sam & Max: Surfin' the Highway`,
    author: 'Steve Purcell',
    image: 'https://m.media-amazon.com/images/I/71XcrBEFzpL._SL1000_.jpg',
    progress: 'reading',
    date: '2025-05-25',
    slug: 'SamAndMaxSurfinTheHighway',
    desc: 'The original comics that lead to the Lucas Arts and Telltale games. Absurdist humor at its finest. The dynamic between the boys is such a fine balance between chaos and cheese. Cheesy chaos, yes. The art is, of course, dynamic and detailed.',
    tags: ['comics'],
  },
  WhatItIs: {
    name: 'What It Is',
    author: 'Lynda Barry',
    image: 'https://m.media-amazon.com/images/I/81r3Bhq6v4L._SL1500_.jpg',
    progress: 'reading',
    date: '2025-05-24',
    purchase: 'https://www.amazon.com/What-Lynda-Barry/dp/1897299354',
    slug: 'WhatItIs',
    desc: "This book vibrates. There's a pitch I hear in my ear as I read it, perhaps it's actually a soft voice... Evocative mix of comics, collage, and personal essays on losing then finding creativity.",
    tags: ['comics', 'creativity'],
  },
  DesigningDataIntensiveApplications: {
    name: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    image: 'https://m.media-amazon.com/images/I/91YfNb49PLL._SL1500_.jpg',
    progress: 'read',
    date: '2025-02-04',
    purchase:
      'https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321/',
    slug: 'DesigningDataIntensiveApplications',
    desc: 'Wildly thorough look at massive scale system design considerations.',
    tags: ['programming'],
  },
  LikeCommentSubscribe: {
    name: 'Like, Comment, Subscribe: How YouTube Conquered the World',
    author: 'Mark Bergen',
    image:
      'http://res.cloudinary.com/cpadilla/image/upload/v1720903630/chrisdpadilla/blog/images/uelzmch7tmwv9vrzwscc.jpg',
    progress: 'read',
    date: '2024-07-06',
    purchase:
      'https://www.amazon.com/Like-Comment-Subscribe-YouTubes-Domination/dp/0593296346',
    slug: 'LikeCommentSubscribe',
    desc: "A Journalist take on the rise of YouTube. Takes a global prospecting exposing some of the uglier sides of the platform's effects. Crazy to see names like John Green and PewDiePie in print.",
    tags: ['non-fiction'],
  },
  LifeOfMeaning: {
    name: 'A Life of Meaning',
    author: 'James Hollis',
    image: 'https://m.media-amazon.com/images/I/81WaMxIe4KL._SL1500_.jpg',
    progress: 'read',
    rating: 8,
    date: '2024-07-02',
    purchase:
      'https://www.amazon.com/Life-Meaning-Relocating-Spiritual-Gravity/dp/1649630727',
    slug: 'LifeOfMeaning',
    desc: `One of Hollis' most recent works. Similar themes return: finding meaning in servicing "what is seeking expression through me?" Some thoughts on embracing our imperfection humanity in the chapter on the Seven Deadly Sins, similar to ideas in [The Happiness Hypothesis](#HappinessHypothesis). Wonderful to listen to the author reading the audiobook!`,
    tags: ['non-fiction'],
  },
  WhatMattersMost: {
    name: 'What Matters Most: Living a More Considered Life',
    author: 'James Hollis',
    image: 'https://m.media-amazon.com/images/I/61rEPsIpzEL._SL1200_.jpg',
    progress: 'read',
    rating: 10,
    date: '2024-06-29',
    purchase: 'https://www.amazon.com/dp/1592404995',
    slug: 'WhatMattersMost',
    desc: `My favorite of Hollis' works so far. An assortment of essays geared towards wrestling with the question of personal meaning. Book goes beyond the usual list of "Friends, family, love, honor, good work, etc." to look more closely at what our unique calling is. A wonderful follow up to ["Finding Meaning in the Second Half of Life"](#FindingMeaningInTheSecondHalfOfLife). The first book asks questions, the second helps move the reader towards finding answers.`,
    tags: ['non-fiction'],
  },
  ProgressiveSightReading: {
    name: 'Progressive Sight Reading Exercises: Piano Technique',
    author: 'Hannah Smith',
    image: 'https://m.media-amazon.com/images/I/81IRMgNKN1L._SL1500_.jpg',
    progress: 'read',
    rating: 8,
    date: '2024-04-29',
    purchase: 'https://www.amazon.com/dp/0793552621',
    slug: 'ProgressiveSightReading',
    desc: `My recommended "Start Here" book for sight reading at the keyboard. I came to this book realizing I was hitting a wall with my playing, looking back and forth at the page and then the keyboard. This won't get you all of the way there, this book focuses on five finger patterns. Though, it's a great place to get going reading several short, bite sized lines.`,
    tags: ['musicresource', 'piano'],
  },
  SuperSightReadingSecrets: {
    name: 'Super Sight-Reading Secrets',
    author: 'Howard Richman ',
    image:
      'https://www.richmanmusicschool.com/wp-content/uploads/2016/08/SSRSLarge-348x450.jpg',
    progress: 'read',
    rating: 9,
    date: '2024-02-25',
    purchase:
      'https://www.richmanmusicschool.com/products/super-sight-reading-secrets',
    slug: 'SuperSightReadingSecrets',
    desc: `A no nonsense book that does exactly what it says on the tin! The best exercises in the book deals with gradually building up a tactile relationship to the keyboard. Progress will seem _very slow_, but the payoff is so worth it! Having played piano for a number of years, I'm only starting to feel I really know the instrument after working through part of this book. A must have for every pianist!!`,
    tags: ['musicresource', 'piano'],
  },
  FindingMeaningInTheSecondHalfOfLife: {
    name: 'Finding Meaning in the Second Half of Life: How to Finally, Really Grow Up',
    author: 'James Hollis',
    image: 'https://m.media-amazon.com/images/I/614GvnvQxML._SL1200_.jpg',
    progress: 'read',
    rating: 9,
    date: '2024-02-13',
    purchase: 'https://www.amazon.com/dp/1592402070',
    slug: 'FindingMeaningInTheSecondHalfOfLife',
    desc: `Picked this up hoping I could get ahead of the curve on my midlife crisis! Essential reading for anyone who's "Reached the end of their scripts for success." Came away with no answers, but better questions. Namely: "What is seeking expression through me?"`,
    tags: ['non-fiction'],
  },
  UnderstandingComics: {
    name: 'Understanding Comics: The Invisible Art',
    author: 'Scott McCloud',
    image: 'https://covers.openlibrary.org/b/id/11855187-L.jpg',
    progress: 'read',
    rating: 9,
    slug: 'UnderstandingComics',
    date: '2024-01-20',
    purchase: 'https://www.amazon.com/dp/006097625X',
    desc: `A primer on art through the lense of how it applies to comics. I learned a great deal about appreciating comics, I learned even more about visual and story-telling mediums as a whole.`,
    tags: ['comics', 'artresource'],
  },
  HarmonicExperience: {
    name: 'Harmonic Experience: Tonal Harmony from Its Natural Origins to Its Modern Expression',
    author: 'W. A. Mathieu',
    image: 'https://m.media-amazon.com/images/I/71YDdeftckL._SL1500_.jpg',
    progress: 'read',
    rating: 8,
    date: '2024-01-04',
    purchase:
      'https://www.amazon.com/Harmonic-Experience-Harmony-Natural-Expression/dp/0892815604',
    slug: 'HarmonicExperience',
    desc: `A true music theory book that focuses on resonance as the basis for understanding harmony. This is not so much a quick road to learning how to compose as much as it is theory in guided practice to understand where our harmonic language comes from. If you enjoyed [Bernstein's introduction to tonal harmony](https://www.youtube.com/watch?v=9HjEAtJXssc&ab_channel=LeonardBernstein), this is an entire textbook exploring that foundation.`,
    tags: ['musicresource', 'theory'],
  },
  FreePlay: {
    name: 'Free Play',
    author: 'Stephen Nachmanovitch',
    image: 'https://m.media-amazon.com/images/I/81QPf6CHRPL._SL1500_.jpg',
    progress: 'read',
    rating: 9,
    date: '2023-11-15',
    purchase:
      'https://www.amazon.com/Free-Play-Improvisation-Life-Art/dp/0874776317',
    slug: 'FreePlay',
    desc: `Wonderful essays on creativity and true improvisation from professional violinist. Highly recommended for any musician, especially those that feel stuck from being classical focused.`,
    tags: ['creativity'],
  },
  FormAndEssence: {
    name: 'Form & Essence',
    author: 'Matthew Hinsley',
    image:
      'http://res.cloudinary.com/cpadilla/image/upload/v1703708187/chrisdpadilla/blog/images/bghzxmoijk0vpc0eaniv.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'FormAndEssence',
    desc: `An antidote to the day-to-day focus on what's quantifiable. A wonderful blending of Stephen Covey and Julia Cameron — fitting for the subject of the book.`,
    tags: ['creativity', 'non-fiction'],
  },
  FellowshipOfTheRing: {
    name: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    image:
      'http://res.cloudinary.com/cpadilla/image/upload/v1703708086/chrisdpadilla/blog/images/hlr5jtbpwsurg5bwi5a6.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'FellowshipOfTheRing',
    desc: `Warm characters, a fantastically grand adventure, and a world so fully realized. Rob Ingles reading and singing the audiobook version is the way to experience this.`,
    tags: ['fiction', 'fantasy'],
  },
  MickeyMouseTrappedOnTreasureIsland: {
    name: `Walt Disney's Mickey Mouse "Trapped On Treasure Island"`,
    author: 'Floyd Gottfredson',
    image:
      'http://res.cloudinary.com/cpadilla/image/upload/v1703708126/chrisdpadilla/blog/images/pohrsvrktakplnngwwoc.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'MickeyMouseTrappedOnTreasureIsland',
    desc: `Stunning adventure comics! The detail in the sets, the grand nature of the story — these strips culminate in a rich novel! Floyd Gottfredson was a major inspiration for Carl Barks.`,
    tags: ['comics'],
  },
  HayaoMiyazaki: {
    name: 'Hayao Miyazaki',
    author: 'Jessica Niebel',
    image: 'https://m.media-amazon.com/images/I/71dgWUHnchL._AC_UY218_.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'HayaoMiyazaki',
    desc: `Beautiful. Absolutely stunning selection of prints, stills, and write ups. An absolute must for any fan of these films. Gorgeous reference.`,
    tags: ['artresource', 'biography'],
  },
  CartoonAnimationPrestonBlair: {
    name: 'Cartoon Animation',
    author: 'Preston Blair',
    image: 'https://covers.openlibrary.org/b/id/8784821-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'CartoonAnimationPrestonBlair',
    desc: `A terrific guide into animation, and not a bad intro to drawing, at that. A brief read, more of a road map rather than a step-by-step guide.`,
    tags: ['artresource'],
  },
  DonaldDuckTheOldCastleSecret: {
    name: 'Donald Duck: The Old Castle Secret',
    author: 'Carl Barks',
    image: 'https://covers.openlibrary.org/b/id/9026572-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'DonaldDuckTheOldCastleSecret',
    desc: `Hugely expressive, phenomenal storytelling, and plenty of genuine chuckles!`,
    tags: ['comics'],
  },
  CalvinAndHobbes: {
    name: 'Calvin & Hobbes',
    author: 'Bill Watterson',
    image: 'https://covers.openlibrary.org/b/id/6916758-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'CalvinAndHobbes',
    desc: `For a modern newspaper strip, these were so dynamic! A fantastic representation of what it felt to be a child, fluidly twisting between a colorful imagination and the world as is.`,
    tags: ['comics'],
  },
  CucumberQuest: {
    name: 'Cucumber Quest',
    author: 'Gigi D.G.',
    image: 'https://covers.openlibrary.org/b/id/12794351-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'CucumberQuest',
    desc: `The art is stunningly gorgeous, the color design and beautiful locales keep me from turning the page!`,
    tags: ['comics'],
  },
  AreYouListening: {
    name: 'Are You Listening?',
    author: 'Tillie Walden',
    image: 'https://covers.openlibrary.org/b/id/9144914-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'AreYouListening',
    desc: `I adore Walden's colors. Like Calvin and Hobbes, there's a back and forth between traveling in a dream and on the open road in the real world.`,
    tags: ['comics'],
  },
  SonicTheHedgehog30thAnniversary: {
    name: 'Sonic the Hedgehog 30th Anniversary Celebration',
    author: 'IDW Publishing',
    image: 'https://covers.openlibrary.org/b/id/12884575-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'SonicTheHedgehog30thAnniversary',
    desc: `I came for the McElroy feature, but stayed for the incredible art. Excellently paneled, posed, and colored.`,
    tags: ['comics'],
  },
  DragonBall: {
    name: 'Dragon Ball',
    author: 'Akira Toriyama',
    image: 'https://covers.openlibrary.org/b/id/14650976-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'DragonBall',
    desc: `The original series was plain old silly! The best part is getting to take in Toriyama's inventive and detailed vehicle design.`,
    tags: ['comics'],
  },
  FullmetalAlchemist: {
    name: 'Fullmetal Alchemist',
    author: 'Hiromu Arakawa',
    image: 'https://covers.openlibrary.org/b/id/6678865-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'FullmetalAlchemist',
    desc: `Really exciting artwork, Al and Ed look so stylish on every page!`,
    tags: ['comics'],
  },
  OnePersonMultipleCareers: {
    name: 'One Person/Multiple Careers: A New Model for Work/Life Success',
    author: 'Marci Alboher',
    image: 'https://covers.openlibrary.org/b/id/1235591-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'OnePersonMultipleCareers',
    desc: `A great collection of interviews and case studies from people whose work isn't easily bound to one job.`,
    tags: ['non-fiction'],
  },
  MakeYourArtNoMatterWhat: {
    name: 'Make Your Art No Matter What: Moving Beyond Creative Hurdles',
    author: 'Beth Pickens',
    image: 'https://covers.openlibrary.org/b/id/10648791-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'MakeYourArtNoMatterWhat',
    desc: `Creative people are those who need their practice so they can wholly show up in all other areas of their lives.`,
    tags: ['creativity', 'non-fiction'],
  },
  HowToFailAtAlmostEverything: {
    name: 'How to Fail at Almost Everything and Still Win Big',
    author: 'Scott Adams',
    image: 'https://covers.openlibrary.org/b/id/7665478-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'HowToFailAtAlmostEverything',
    desc: `General life advice mixed with Adams' life story, including his navigation through bouts of focal dystonia. Entertaining and insightful!`,
    tags: ['non-fiction'],
  },
  TheGiftsOfImperfection: {
    name: 'The Gifts of Imperfection',
    author: 'Brené Brown',
    image: 'https://covers.openlibrary.org/b/id/7414597-L.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'TheGiftsOfImperfection',
    desc: `Even after years of Brown's work being in the cultural conversation, this little volume still opens up new insight on authentic living on re-reading.`,
    tags: ['non-fiction'],
  },
  TheAlchemist: {
    name: 'The Alchemist',
    author: 'Paulo Coelho',
    image: 'https://m.media-amazon.com/images/I/51Z0nLAfLmL.jpg',
    progress: 'read',
    date: '2023-06-01',
    slug: 'TheAlchemist',
    desc: `A beautiful journey that illustrates how much richer the world is when we pursue our own personal inspirations and callings, grand or simple.`,
    tags: ['fiction', 'creativity'],
  },
  PaintingAsAPastime: {
    name: 'Painting As a Pastime',
    author: 'Winston S. Churchill',
    image: 'https://m.media-amazon.com/images/I/514R5ZI7SnL._SL1280_.jpg',
    progress: 'read',
    rating: 8,
    date: '2023-05-20',
    purchase:
      'https://www.amazon.com/Painting-Pastime-Sir-Winston-Churchill/dp/1906509336',
    slug: 'PaintingAsAPastime',
    desc: `A love letter to color and light from an enthusiastic amateur.`,
    tags: ['creativity'],
  },
  ASlipOfTheKeyboard: {
    name: 'A Slip of the Keyboard: Collected Nonfiction',
    author: 'Terry Pratchett',
    image: 'https://m.media-amazon.com/images/I/719T6d--xbL._SL1200_.jpg',
    progress: 'read',
    rating: 7,
    date: '2023-01-10',
    purchase:
      'https://www.amazon.com/Slip-Keyboard-Collected-Nonfiction/dp/0804169225',
    slug: 'ASlipOfTheKeyboard',
    desc: `Wonderful collection. Great for true fans of his fiction work. The biography is a deeper dive, though these are great as quick glimpses behind the curtain, presented by the author himself.`,
    tags: ['non-fiction'],
  },
  ALifeInFootnotes: {
    name: 'Terry Pratchett: A Life With Footnotes: The Official Biography',
    author: 'Rob Wilkins',
    image: 'https://m.media-amazon.com/images/I/81fFbN1mnYL._SL1500_.jpg',
    progress: 'read',
    rating: 9,
    date: '2022-10-23',
    purchase:
      'https://www.amazon.com/Terry-Pratchett-Footnotes-Official-Biography/dp/0857526634',
    slug: 'ALifeInFootnotes',
    desc: `Beautifully written biography of a favorite author, written by his assistant. A wonderful window into the man behind Discworld. A must read for any fan!`,
    tags: ['biography'],
  },
  // 2022 Books
  ThePragmaticProgrammer: {
    name: 'The Pragmatic Programmer',
    author: 'Andy Hunt and Dave Thomas',
    image: 'https://padilla-media.s3.amazonaws.com/books/pragmatic.jpeg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ThePragmaticProgrammer',
    desc: `Timeless principles for developing software. Such a wide range of topics relating to the job are covered, it feels like a must read for anyone new to the field! How to prototype, how to maintain software, how to manage projects, communicating with non-technical collaborators. It's all here!`,
    tags: ['programming'],
  },
  PragmaticThinkingAndLearning: {
    name: 'Pragmatic Thinking and Learning',
    author: 'Andy Hunt',
    image:
      'https://padilla-media.s3.amazonaws.com/books/pragmaticThinking.jpeg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'PragmaticThinkingAndLearning',
    desc: `Could have easily been titled: How to Learn Anything. A very thorough guide on utilizing the whole brain to gain mastery in a new thought-driven domain. Excellent read, plenty of great exercises for really connecting ideas.`,
    tags: ['programming', 'non-fiction', 'learning'],
  },
  ThePassionateProgrammer: {
    name: 'The Passionate Programmer',
    author: 'Chad Fowler',
    image: 'https://padilla-media.s3.amazonaws.com/books/passionateprog.jpeg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ThePassionateProgrammer',
    desc: `Career advice for software engineering from a former full time sax player gone programmer. A great meta-framework for how to continue to learn and grow in the field.`,
    tags: ['programming'],
  },
  ThePersonalMBA: {
    name: 'The Personal MBA',
    author: 'Josh Kaufman',
    image: 'https://padilla-media.s3.amazonaws.com/books/personalmba.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ThePersonalMBA',
    desc: `Part nuts-and-bolts of business, and part addressing the mindset and personal psychology in taking on such a full bodied endeavor. It's also a great springboard into his reading list of 100 other great books for deeper diving.`,
    tags: ['non-fiction', 'business'],
  },
  AskIwata: {
    name: 'Ask Iwata',
    author: 'Satoru Iwata',
    image: 'https://padilla-media.s3.amazonaws.com/books/askiwata.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'AskIwata',
    desc: `Not a full blown biography, but pieces of interviews Iwata has given that are strung together to tell his story in broad strokes. A surprisingly insightful read on leadership, creativity, and management. And Iwata's story is simply legendary.`,
    tags: ['biography', 'technology'],
  },
  ShowYourWork: {
    name: 'Show Your Work',
    author: 'Austin Kleon',
    image: 'https://padilla-media.s3.amazonaws.com/books/showyourwork.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ShowYourWork',
    desc: `"How would Brian Eno write a Content Marketing book", as the author puts it. He writes about reframing "marketing" as "community building", being part of a scene over screaming into the void.`,
    tags: ['creativity'],
  },
  ThePrincipleOf18: {
    name: 'The Principle of 18',
    author: 'Eyal Danon',
    image: 'https://padilla-media.s3.amazonaws.com/books/po18.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ThePrincipleOf18',
    desc: `A life changer, honestly. The gist is that there are 5 phases of life spanning 18 years. Dreamer, Explorer, Builder, Mentor, and Giver. Each builds on the previous, and each has different major motivations.`,
    tags: ['non-fiction'],
  },
  TheTimeParadox: {
    name: 'The Time Paradox',
    author: 'Philip Zimbardo',
    image: 'https://padilla-media.s3.amazonaws.com/books/timeParadox.jpeg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'TheTimeParadox',
    desc: `Interesting lens on how the way we perceive time shapes us. Future focused folks are the sort that develop lists, set goals, and achieve them. Present focused people, alternatively, are "in the moment", enjoy richness and are generally more playful.`,
    tags: ['non-fiction'],
  },
  BigMagic: {
    name: 'Big Magic',
    author: 'Elizabeth Gilbert',
    image: 'https://padilla-media.s3.amazonaws.com/books/bigmagic.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'BigMagic',
    desc: `One of my favorite books on living creatively. The secret is bouncing between serious, regular dedication to what you care about doing, and also not taking it that seriously, making the work playful as you do it.`,
    tags: ['creativity'],
  },
  HalLeonardJazzPianoMethod: {
    name: 'Hal Leonard Jazz Piano Method',
    author: 'Mark Davis',
    image: 'https://halleonard-coverimages.s3.amazonaws.com/wl/00131102-wl.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'HalLeonardJazzPianoMethod',
    desc: `The first Jazz book I've picked up that actually takes you from zero to improvising. Too many other books I've read assume some sort of prior knowledge or experience. A great starting place.`,
    tags: ['musicresource', 'jazz', 'piano'],
  },
  TheJazzPianoBook: {
    name: 'The Jazz Piano Book',
    author: 'Mark Levine',
    image: 'https://www.shermusic.com/new/images/0961470151.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'TheJazzPianoBook',
    desc: `A good reference for the intermediate and beyond jazz pianist. Not terribly beginner friendly, see other materials if just starting out.`,
    tags: ['musicresource', 'jazz', 'piano'],
  },
  ParkeningGuitarMethod: {
    name: 'Christopher Parkening Guitar Method',
    author: 'Christopher Parkening',
    image: 'https://m.media-amazon.com/images/I/714RIh8Hj+L._AC_UY218_.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'ParkeningGuitarMethod',
    desc: `_The_ classical guitar method. Lovely for finger picking practice.`,
    tags: ['musicresource', 'guitar'],
  },
  BerkleeGuitarMethod: {
    name: 'A Modern Method for guitar',
    author: 'William Leavitt',
    image: 'https://halleonard-coverimages.s3.amazonaws.com/wl/00292990-wl.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'BerkleeGuitarMethod',
    desc: `College-level method book used by the Berklee School. Excellent resource for developing the ability to read sheet music and proprioception in each hand.`,
    tags: ['musicresource', 'guitar'],
  },
  HalLeonardGuitarMethod: {
    name: 'Hal Leonard Guitar Method',
    author: 'Will Schmid and Greg Koch',
    image: 'https://padilla-media.s3.amazonaws.com/books/halleonardguitar.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'HalLeonardGuitarMethod',
    desc: `Nothing beats a good ol' fashioned method book! This one focuses pretty heavily on lead guitar. Lots of spirituals and traditional tunes. Playing these tuneful lines early on helps melodic playing and getting familiar with the notes on the guitar.`,
    tags: ['musicresource', 'guitar'],
  },
  RemixingTheClassroom: {
    name: 'Remixing the Classroom',
    author: 'Randall Everett Allsup',
    image:
      'https://padilla-media.s3.amazonaws.com/books/remixingTheClassroom.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'RemixingTheClassroom',
    desc: `An argument for how classroom music favors teacher-lead instruction and skill development in favor of nurturing creativity and really fostering a life long interest in engaging with music.`,
    tags: ['music', 'non-fiction', 'education'],
  },
  LaserwriterII: {
    name: 'Laserwriter II',
    author: 'Tamara Shopsin',
    image: 'https://padilla-media.s3.amazonaws.com/books/laserwriterII.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'LaserwriterII',
    desc: `Quirky characters, old computer hardware, and moments of surrealism.`,
    tags: ['fiction'],
  },
  TheLightFantastic: {
    name: 'The Light Fantastic',
    author: 'Terry Pratchett',
    image: 'https://padilla-media.s3.amazonaws.com/books/TLF.jpg',
    progress: 'read',
    date: '2022-06-01',
    slug: 'TheLightFantastic',
    desc: `Still wildly funny, but there's a more serious tone at the start that quickly reshapes even in the next book onward. If these books were illustrations, later books are fully colored in more of a cartoony style, and this one was done a darker, more energetic ink style.`,
    tags: ['fiction', 'fantasy'],
  },
  FourThousandWeeks: {
    name: 'Four Thousand Weeks: Time Management for Mortals',
    author: 'Oliver Burkeman',
    image: 'https://padilla-media.s3.amazonaws.com/books/4000weeks.jpg',
    progress: 'read',
    date: '2022-06-01',
    purchase:
      'https://www.amazon.com/Four-Thousand-Weeks-Management-Mortals/dp/1250849357',
    slug: 'FourThousandWeeks',
    desc: 'A countermelody to the productivity driven ethos of modern self help. Highly recommended!',
    tags: ['non-fiction'],
  },
  ListeningBook: {
    name: 'The Listening Book: Discovering Your Own Music',
    author: 'W. A. Mathieu',
    image: 'https://padilla-media.s3.amazonaws.com/books/listeningbook.jpeg',
    progress: 'read',
    date: '2022-06-01',
    purchase: 'https://www.amazon.com/gp/product/159030831X/',
    slug: 'ListeningBook',
    desc: `Everyone should read this! Even non musicians. The book takes the pure meditative quality of listening to and reveling in sound from the start and further combs towards practicing music. Absolutely beautiful. So many wonderful insights on our relation to sound and being a creative musician in the world.`,
    tags: ['creativity'],
  },
  GestureDrawingForAnimation: {
    name: 'Gesture Drawing for Animation',
    author: 'Walt Stanchfield',
    image: 'https://padilla-media.s3.amazonaws.com/books/gesturedrawing.jpg',
    progress: 'read',
    date: '2022-06-01',
    purchase: 'https://www.amazon.com/gp/product/B08KQ58SD3',
    slug: 'GestureDrawingForAnimation',
    desc: `Inspiring essays on capturing the essence of the figure from a disney veteran. One of my personal favorites.`,
    tags: ['artresource', 'drawing'],
  },
  FunWithAPencil: {
    name: 'Fun With A Pencil',
    author: 'Andrew Loomis',
    image: 'https://covers.openlibrary.org/b/id/7089781-L.jpg',
    progress: 'read',
    date: '2022-06-01',
    purchase:
      'https://www.amazon.com/Fun-Pencil-Everybody-Easily-Learn/dp/0857687603',
    slug: 'FunWithAPencil',
    desc: `A classic drawing book in the commercial illustrator style. All of Loomis' materials are great. They are, perhaps, overly measured. The best benefit from these, I would say, is the material on constructing the figure.`,
    tags: ['artresource', 'drawing'],
  },
  FigureDrawingForAllItsWorth: {
    name: "Figure Drawing for All It's Worth",
    author: 'Andrew Loomis',
    image: 'https://covers.openlibrary.org/b/id/8987785-L.jpg',
    progress: 'read',
    date: '2022-06-01',
    purchase:
      'https://www.amazon.com/Figure-Drawing-All-Its-Worth/dp/0857680986',
    slug: 'FigureDrawingForAllItsWorth',
    desc: `More inspiring reference.`,
    tags: ['artresource', 'drawing'],
  },
  HappinessHypothesis: {
    name: 'The Happiness Hypothesis: Finding Modern Truth in Ancient Wisdom',
    author: 'Jonathan Haidt',
    image: 'https://m.media-amazon.com/images/I/81zC1pSRNIL._SL1500_.jpg',
    progress: 'read',
    rating: 8,
    date: '2021-07-19',
    purchase:
      'https://www.amazon.com/Happiness-Hypothesis-Finding-Modern-Ancient/dp/0465028020',
    slug: 'HappinessHypothesis',
    desc: `An interesting review of research that supports the author's proposed equation for what truly makes us happy. Makes case that there may be no objective meaning to life, we find meaning in the context within our lives.`,
    tags: ['non-fiction'],
  },
  RealityIsBroken: {
    name: 'Reality Is Broken: Why Games Make Us Better and How They Can Change the World',
    author: 'Jane McGonigal',
    image: 'https://m.media-amazon.com/images/I/8192f4oUxIL._SL1500_.jpg',
    progress: 'read',
    rating: 7,
    date: '2020-09-15',
    purchase:
      'https://www.amazon.com/Reality-Broken-Games-Better-Change/dp/0143120611',
    slug: 'RealityIsBroken',
    desc: `Fun read on how games improve our lives, and how they can be a model for rethinking our systems and organizations IRL. The case studies date the book, though the principles and takeaways are evergreen.`,
    tags: ['non-fiction'],
  },
  TheDesignOfEverydayThings: {
    name: 'The Design of Everyday Things',
    author: 'Don Norman',
    image: 'https://m.media-amazon.com/images/I/71LBfNStp9L._AC_UY218_.jpg',
    progress: 'read',
    date: '2019-11-15',
    purchase:
      'https://www.amazon.com/Design-Everyday-Things-Revised-Expanded-ebook/dp/B00E257T6C',
    slug: 'TheDesignOfEverydayThings',
    desc: `Design principles for anyone who makes tools for people. Translates beautifully to software.`,
    tags: ['design', 'non-fiction', 'programming'],
  },
  EloquentJavaScript: {
    name: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    image: 'https://covers.openlibrary.org/b/id/8513405-M.jpg',
    progress: 'read',
    date: '2019-06-01',
    purchase: 'https://eloquentjavascript.net/',
    slug: 'EloquentJavaScript',
    desc: `A great introduction to one of the most widely used scripting languages out there! Well written with excellent examples to follow along with.`,
    tags: ['programming'],
  },
  TheArtistsWay: {
    name: "The Artist's Way",
    author: 'Julia Cameron',
    image: 'https://covers.openlibrary.org/b/id/10840008-L.jpg',
    progress: 'read',
    date: '2019-06-01',
    purchase:
      'https://www.amazon.com/Artists-Way-25th-Anniversary-Expanded/dp/0143129252',
    slug: 'TheArtistsWay',
    desc: `An antidote to creative block. Highly recommend reading this and following the exercises as a 12 week program. The juices will begin to flow!`,
    tags: ['creativity'],
  },
  AmericanGods: {
    name: 'American Gods',
    author: 'Neil Gaiman',
    image: 'https://m.media-amazon.com/images/I/716LpMKQ3iL._SL1500_.jpg',
    progress: 'read',
    rating: 8,
    date: '2018-11-29',
    purchase: 'https://www.amazon.com/American-Gods-Neil-Gaiman/dp/0380973650',
    slug: 'AmericanGods',
    desc: `"Meandering" in the author's words, in the best way.`,
    tags: ['fiction'],
  },
  AnythingYouWant: {
    name: 'Anything You Want',
    author: 'Derek Sivers',
    desc: 'Business advice from an early dot com success story and all-around interesting thinker.',
    progress: 'read',
    slug: 'AnythingYouWant',
    tags: ['non-fiction', 'business'],
    image: 'https://m.media-amazon.com/images/I/61P+7owVcML._SY425_.jpg',
    date: '2018-02-19',
  },
  StealLikeAnArtist: {
    name: 'Steal Like An Artist',
    author: 'Austin Kleon',
    image: 'https://covers.openlibrary.org/b/id/7284187-L.jpg',
    progress: 'read',
    date: '2016-06-01',
    purchase:
      'https://www.amazon.com/Steal-Like-Artist-Things-Creative/dp/0761169253',
    slug: 'StealLikeAnArtist',
    desc: `A little burst of inspiration. If you're looking for a permission slip to go after what you care about, here it is!`,
    tags: ['creativity'],
  },
};
