export const linksFeed = [
  {
    url: 'https://www.youtube.com/watch?v=SUd2w7ONJXA',
    title: 'Brazil – Beirut',
    description: `An old favorite. Zach Condon's voice is spectacular.`,
    tags: ['music', 'indie', 'bossa nova'],
    dateAdded: '2025-11-03 09:14:03',
  },
  {
    url: 'https://en.wikipedia.org/wiki/Bricolage',
    title: 'Bricolage - Wikipedia',
    description: `Today's vocab word for a way of creating that brings together "materials available or on hand".`,
    tags: ['creativity', 'making'],
    dateAdded: '2025-11-02 11:20:15',
  },
  {
    url: 'https://shmuplations.com/gamemusic1986/',
    title: '1986 Game Music Round Table Interview',
    description:
      'Great translation from Schmuplations. The cartoons included are fantastic.',
    tags: ['video games', 'music', 'interview'],
    dateAdded: '2025-11-02 10:53:57',
  },
  {
    url: 'https://austinkleon.substack.com/p/the-art-of-the-newsletter',
    title: 'The Art of the Newsletter – Austin Kleon',
    description: `Several gems here. Biggest one is that in modernity we take in so much input, but don't have a place to put it. A practice is great for that.`,
    tags: ['writing', 'newsletters'],
    dateAdded: '2025-10-30 10:15:00',
  },
  {
    url: 'https://frontendmasters.com/blog/50-reasons-to-build-a-website/',
    title: '50 Reasons to Build a Website – Chris Coyier',
    description: `Fun list!`,
    tags: ['webcrafting'],
    dateAdded: '2025-10-29 10:12:33',
  },
  {
    url: 'https://www.robinsloan.com/lab/shape-of-creative-ideas/',
    title: 'The shape of creative ideas – Robin Sloan',
    description: `Fellow Animation Obsessive Newsletter enjoyer Robin Sloan highlights a great observation on how craft and genre are the beginnings of a work, not necessarily the emotional impact. Can attest to the truth in this.`,
    tags: ['creativity', 'animation'],
    dateAdded: '2025-10-23 14:34:54',
  },
  {
    url: 'https://seths.blog/2025/10/the-writers-room/',
    title: "The Writer's Room – Seth's Blog",
    description: `One of the more level-headed takes I've seen on responsibly incorporating AI into your work.`,
    tags: ['creativity', 'AI'],
    dateAdded: '2025-10-21 07:55:12',
  },
  {
    url: 'https://commons.wikimedia.org/wiki/File:Dunning%E2%80%93Kruger_Effect_01.svg#/media/File:Dunning%E2%80%93Kruger_Effect_01.svg',
    title: 'Dunning Kruger Effect Graph (Exagerated)',
    description: `TIL this graph is in fact _not_ the correct representation. However, it's the graph that _feels_ the most relatable.`,
    tags: ['psychology', 'graphs', 'cognitive bias', 'learning'],
    dateAdded: '2025-10-20 21:19:22',
  },
  {
    url: 'https://www.youtube.com/watch?v=mSe1K82FWV0',
    title: 'Takashi Yoshimatsu - Complete Pleiades Dances',
    description: `I was introduced to Yoshimatsu's music through his Fuzzy Bird Sonata for Saxophone and Piano in college. These piano pieces are each glimmering gems. Definitely going on the "to-learn" list!`,
    tags: ['music', 'classical', 'piano'],
    dateAdded: '2025-10-17 16:43:22',
  },
  {
    url: 'https://slate.com/technology/2021/05/john-green-anthropocene-reviewed-excerpt-internet.html',
    title: 'John Green – The Internet: A Review',
    description: `"I have wonderful memories of that summer, and also traumatic ones. A few years ago, I ran into an old friend, who said of our high school, 'It saved my life. But it also did a lot of other things.' So, too, with the internet."`,
    tags: ['internet', 'articles', 'writing'],
    dateAdded: '2025-10-05 19:12:18',
  },
  {
    url: 'https://daverupert.com/2025/09/why-would-anybody-start-a-website/',
    title: 'Why would anybody start a website?',
    description: `It's fun and I like it! And so does Dave.`,
    tags: ['webcrafting', 'personal websites', 'writing'],
    dateAdded: '2025-09-18 15:50:19',
  },
  {
    url: 'https://youtu.be/xCFEk6Y8TmM?si=yAD6jSK_L4RFrZdH',
    title: 'Luciano Pavarotti - La Donna È Mobile (Rigoletto)',
    description: `Been on an Aria kick, particularly while driving with the mountains in view. If you only listen to one, this should be one of them!`,
    tags: ['music', 'classical', 'opera'],
    dateAdded: '2025-09-15 21:49:26',
  },
  {
    url: 'https://youtu.be/fRg0K5rgXog?si=6jCbLWhX3M8YXEEv&t=7',
    title: `Beethoven Symphony No. 6 "Pastorale" And Egmont Overture Op.68 - London Philarmonic Orchestra`,
    description: `Beautiful.`,
    tags: ['music', 'classical'],
    dateAdded: '2025-08-29 16:04:16',
  },
  {
    url: 'https://www.youtube.com/watch?v=MFBOtWq7dsE',
    title: 'Windows96 – Plume Valley',
    description: `Few capture the mood quite like Windows96.`,
    tags: ['music', 'chillwave', 'vaporwave'],
    dateAdded: '2025-08-20 16:04:16',
  },
  {
    url: 'https://youtu.be/9fvGgaqo61s?si=PGpF9jNfnbGXx680',
    title: 'Tomoyuki Asakawa - Endless Tide',
    description: `Had to save this one for the track "Sazameki" ("Ripple"). Gorgeous flute and harp duo.`,
    tags: ['music', 'ambient'],
    dateAdded: '2025-07-23 16:04:16',
  },
  {
    url: 'https://en.wikipedia.org/wiki/Trojan_Room_coffee_pot',
    title: 'Trojan Room Coffee Pot',
    description: `TIL what the first webcam was used for!`,
    tags: ['web'],
    dateAdded: '2025-07-17 12:32:44',
  },
  {
    url: 'https://topazcomics.com/one-shots/a-mini-guide-to-rss-feeds-1/',
    title: 'A Mini Guide to RSS Feeds',
    description: `Fun comic on using RSS feeds!`,
    tags: ['webcomics', 'rss'],
    dateAdded: '2025-07-17 12:28:02',
  },
  {
    url: 'https://austinkleon.com/2025/06/05/a-peek-inside-my-pocket-notebook/',
    title: 'Austin Kleon Pocket Notebook',
    description: `"The 'Deep Work' and '10,000 Hours' people have poisoned the creative mind with the idea that your great work will be the result of getting serious. So many of my good ideas come from what looks like goofing off, wasting time. Art is play. There's no way to tell what's deep or shallow until you play with the idea."`,
    tags: ['writing', 'Austin Kleon', 'play'],
    dateAdded: '2025-07-13 09:01:59',
  },
  {
    url: 'https://austinkleon.com/2025/07/08/typewriter-interview-with-laura-lippman/',
    title: 'Austin Kleon Typewriter Interview with Laura Lippman',
    description: `"Be ruthlessly honest with yourself: Do you want to write or do you just want to publish? ...The perks of publishing are cotton-candy pleasures. Writing is where the real joy happens..."`,
    tags: ['writing', 'Austin Kleon', 'process'],
    dateAdded: '2025-07-13 09:01:59',
  },
  {
    url: 'https://magicalgametime.com/post/7326125712/ive-been-talking-about-earthbound-so-much-i',
    title: 'Zac Gorman Earthbound Comics',
    description: `Looking back fondly on these lately.`,
    tags: ['comics', 'webcomics'],
    dateAdded: '2025-07-07 22:22:42',
  },
  {
    url: 'https://www.exocomics.com/',
    title: 'Extra Ordinary Comics',
    description:
      'Cutie-patootie comics by Li Chen. Just revisiting these after over a decade. Still a delight!',
    tags: ['comics', 'webcomics'],
    dateAdded: '2025-07-03 10:57:57',
  },
  {
    url: 'https://www.youtube.com/watch?v=Z3m7HXeiHpg&ab_channel=shouldbeasleep',
    title: 'Hiroshi Yoshimura - Wet Land',
    description:
      'More gorgeous ambient music from Yoshimura. Favorite: Singing Stream (Spring Mix)',
    tags: ['music', 'ambient'],
    dateAdded: '2025-06-24 15:58:19',
  },
  {
    url: 'https://www.youtube.com/watch?v=o4yyHQmnJWo&ab_channel=Trancequarium',
    title: 'Producer 03 – Blu Mar Ten',
    description: `Exquisite Liquid Drum and Bass. These Producer series albums are such nice compilations.`,
    tags: [
      'music',
      'ambient',
      'drum and bass',
      'liquid drum and bass',
      'album',
    ],
    dateAdded: '2025-06-24 10:51:23',
  },
  {
    url: 'https://youtu.be/8DVD-Z2NV_w?si=Bzcf3NNCtPfPubVD',
    title: 'Hiroshi Yoshimura – Four Post Cards',
    description: 'Beautiful ambient music.',
    tags: ['music', 'ambient'],
    dateAdded: '2025-06-17 08:28:54',
  },
  {
    url: 'https://discussions.apple.com/thread/253922769?answerId=257361517022&sortBy=rank#257361517022',
    title: 'How to Increase Video Volume via CLI',
    description: `Thanks terryb on the Apple Discussions forum! I usually need to crank personal recordings up 15db.`,
    tags: ['video', 'cli'],
    dateAdded: '2025-06-06 17:41:10',
  },
  {
    url: 'https://chypho.bandcamp.com/album/episodes-in-oceanography',
    title: 'Episodes in Oceanography – Chypho',
    description: `A while back I listened to a fair amount of albums from the 80's Japanese ambient music movement. (By Takashi Kokubo and Hiroshi Yoshimura namely.) Chypho has captured that magic here in a way that feels both true to the original style and also an organic growth from it.`,
    tags: ['music', 'ambient', 'environmental', 'album'],
    dateAdded: '2025-06-06 10:39:56',
  },
  {
    url: 'https://austinkleon.substack.com/p/3-thoughts-while-pushing-a-wheelbarrow',
    title: '3 thoughts while pushing a wheelbarrow – Austin Kleon',
    description: `"The computer used to mean the world to me. The computer was a portal to the world I wished to be in. Times change, and I no longer wish to be in contact with much of the world that’s in my computer. Yard work is a wonderful distraction."`,
    tags: ['articles', 'computers', 'writing'],
    dateAdded: '2025-06-05 11:22:46',
  },
  {
    url: 'https://youtu.be/7lEG-c6lv0k?si=f4f8rncIOq9d2nsM',
    title: 'Castle City — Wave Race OST',
    description: `Very Takanaka in my mind.`,
    tags: ['music', 'video games'],
    dateAdded: '2025-06-05 11:20:46',
  },
  {
    url: 'https://rachsmith.com/pages-cms/',
    title: 'Pages CMS',
    description: `Rach Smith shares her workflow for micro-blog sized posts. Pretty easy setup by the looks of it!`,
    tags: ['webcrafting', 'blogging', 'cms'],
    dateAdded: '2025-06-05 11:19:01',
  },
  {
    url: 'https://www.youtube.com/watch?v=fwa7-gmjMgA&t=2694s&ab_channel=NiwamoriPiano',
    title: 'occasional strange dream',
    description: `Piano music for this rainy evening.`,
    tags: ['music', 'piano'],
    dateAdded: '2025-06-04 20:24:29',
  },
  {
    url: 'https://www.henrikkarlsson.xyz/p/private-notebooks',
    title: 'On the pleasure of reading private notebooks',
    description: `Henrik Karlsson on reading the organic sprawl of private notes. "Browsing through private notes feels more like participating in a happening than reading a piece of literature: this is what happened, more or less in real time, inside another human. Their beauty has more in common with the beauty of nature than the beauty of art. It is sprawling, strange, tangled, and confusing—but the overall work has a deep structure to it that art can’t imitate." Digital Gardeners rejoice: the more organic, the better!`,
    tags: ['digital gardening', 'writing', 'notes'],
    dateAdded: '2025-06-02 20:51:37',
  },
  {
    url: 'https://theculturewedeserve.substack.com/p/culture-digested-the-creation-plot?utm_source=post-email-title&publication_id=1197232&post_id=164036193&utm_campaign=email-post-title&isFreemail=true&r=44lp0&triedRedirect=true&utm_medium=email',
    title: 'Culture, Digested: The Creation Plot',
    description: `On the origin and proliferation of the cultural narrative around "being creative" as a hero's journey. "Unlike stories about artistic creation of the past... the goal of the contemporary story of creators is not to create something good but to achieve success..." And then later: "...And all of this would be true if any of these products were art. But they’re not. They’re hagiography. They are devoted to turning the author into a sainted artist, toiling away for the good of mankind"`,
    tags: ['creativity', 'article'],
    dateAdded: '2025-06-01 15:40:26',
  },
  {
    url: 'https://youtu.be/ee8IivQyu_4',
    title: 'The unseen history of Myst | VGHF Library Highlights',
    description:
      'Overview of a stunning amount of archived footage found across the development of the Myst series! View the archive [here](https://archive.gamehistory.org/folder/22cf9aa2-812b-4f39-b42e-e87a3c153b8c). Seeing high-resolution recordings of original interviews is simply amazing!',
    tags: ['video games', 'myst'],
    dateAdded: '2025-05-28 16:20:38',
  },
  {
    url: 'https://mykal.codes/posts/cool-tools-cli-edition',
    title: 'Cool Tools: CLI Edition',
    description:
      'Cool write up by Mykal Machon on CLI tools that are full blown applications!',
    tags: ['development', 'tools', 'cli'],
    dateAdded: '2025-05-26 13:38:06',
  },
  {
    url: 'https://youtu.be/68JBmgIujIc?si=FYzVmpNZQtpNaER2',
    title: 'Anand Wilder – Appointment in Samarra',
    description:
      'Mr. Yeasayer making delicious use of sitar, saxophone, and synth winds.',
    tags: ['music', 'indie', 'song'],
    dateAdded: '2025-05-24 21:34:22',
  },
  {
    url: 'https://www.youtube.com/watch?v=pr6t6AJ6lho&ab_channel=ArpWireTV',
    title: 'dream OS',
    description:
      'Spacey frutiger aero album. Bells for days. Favorite track: digital ocean.',
    tags: ['music', 'frutiger aero', 'album'],
    dateAdded: '2025-05-23 10:49:52',
  },
  {
    url: 'https://www.discogs.com/release/14395659-Bach-Academy-Of-St-Martin-in-the-Fields-Sir-Neville-Marriner-The-Brandenburg-Concertos-The-Orchestra',
    title:
      'Academy of St. Martin in the Fields – Bach Brandonburg Concertos / The Orchestral Suites',
    description: "No. 3 is where it's at!",
    tags: ['music', 'classical', 'album'],
    dateAdded: '2025-05-22 10:48:52',
  },
  {
    url: 'https://www.youtube.com/watch?v=Xm5OiB3CPxg&ab_channel=LGR',
    title: `LGR Tech Tales - Y2K: The Year 2000 Problem`,
    description: `This link is Y2K compliant!`,
    tags: ['vintage tech'],
    dateAdded: '2025-05-21 22:34:58',
  },
  {
    url: 'https://www.cameronsworld.net/',
    title: `Cameron's World`,
    description: `Delightful art piece dedicated to Geocities era websites. Be sure to click around!`,
    tags: ['early internet', 'websites'],
    dateAdded: '2025-05-21 19:41:47',
  },
  {
    url: 'https://archive.org/details/the-apple-ii-age',
    title: `The Apple II Age Reading`,
    description: `Very excited to read Laine Nooney's book. Very compelling introduction read by the author. As someone who admittedly wears rose-colored glasses when looking at older tech, I'm excited for the multiple perspectives unearthed by Nooney's book. Cool to see the Internet Archive cited as a major source for an academic book, as well!`,
    tags: ['vintage tech', 'books'],
    dateAdded: '2025-05-21 19:40:47',
  },
  {
    url: 'https://www.youtube.com/watch?app=desktop&v=oRQfvEXj_gc&ab_channel=Let%27sTalkAboutMathRock',
    title: `7 Essential Beginner Math Rock / Midwest Emo Riffs by Let's Talk About Math Rock`,
    description: `Been working my way through this. Great curation.`,
    tags: ['guitar', 'midwest emo', 'math rock'],
    dateAdded: '2025-05-21 17:54:49',
  },
  {
    url: 'https://archive.org/details/a-goofy-movie-models/page/n9/mode/2up',
    title: `Disney's A Goofy Movie: Production Model Sheets`,
    description: `Miranda and I watched Not Just a Goof, the Goofy Movie documentary. I dug around to see if there were any art books out there. Searching dug up the Goofy Movie model sheets here.`,
    tags: ['animation', 'art'],
    dateAdded: '2025-05-21 17:53:49',
  },
  {
    url: 'https://www.youtube.com/watch?v=h4wWITMUop0',
    title: `A Brief History of... Myst`,
    description: `Overview of Cyan and the Myst franchise beyond the first title. "A strange fate for what was once the best-selling, most popular game of all time."`,
    tags: ['video games'],
    dateAdded: '2025-05-21 17:52:49',
  },
  {
    url: 'https://www.youtube.com/watch?v=sOJMTtkkijY&ab_channel=LouieZong',
    title: `Louie's Drawing Fun Times - Episode 1`,
    description: `A quick peak behind the digital painting curtain. My workflow is largely similar, given that he's an inspiration!`,
    tags: ['artresources', 'digital painting'],
    dateAdded: '2025-05-21 17:51:49',
  },
  {
    url: 'https://zonelets.net/',
    title: 'Zonelets',
    description: `_"Making text appear online is both utterly basic and infinitely powerful. If you write something down, and someone else reads it from afar... that's it! That's the whole thing! You've done it!"_ Agreed, simple yet powerful and fun!`,
    tags: ['websites', 'webcrafting'],
    dateAdded: '2025-05-21 17:50:49',
  },
  {
    url: 'https://melonking.net/',
    title: 'Melon King',
    description:
      'A wildly creative site bringing the best of the old web to the new.',
    tags: ['websites', 'webcrafting'],
    dateAdded: '2025-05-21 17:49:49',
  },
];
