export const primaryTags = ['Tech', 'Notes', 'Books', 'Music', 'Art', 'Scrapbook'];

export const techTags = [
  'Testing',
  'React',
  'Node',
  'AWS',
  'Architecture',
  'Analytics',
  'JavaScript',
  'Python',
  'CSS',
  'MongoDB',
  'Database',
  'HTML',
  'Project',
  'Backend',
  'Meta',
  'Git',
  'Linux',
  'Express',
  'GraphQL',
  'oldgold',
  'csharp',
];
